# Generated by Django 5.2.12 on 2026-06-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0003_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='otp',
            field=models.CharField(max_length=64),
        ),
    ]
