# Generated by Django 5.1.2 on 2026-06-05 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0004_otpverification_attempts_alter_otpverification_otp'),
        ('store', '0007_delete_profile'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='Profile',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('date_modified', models.DateTimeField(auto_now=True)),
                        ('address', models.CharField(blank=True, max_length=200)),
                        ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'db_table': 'store_profile',
                    },
                ),
            ]
        )
    ]
