# Generated by Django 5.1.2 on 2026-06-05 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_is_sale_alter_product_name_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RemoveField(
                    model_name='profile',
                    name='phone',
                ),
                migrations.RemoveField(
                    model_name='profile',
                    name='old_cart',
                ),
            ],
            state_operations=[
                migrations.DeleteModel(
                    name='Profile',
                ),
            ]
        )
    ]
