# Generated by Django 5.1.2 on 2024-12-24 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
