# Generated by Django 5.1.4 on 2025-01-06 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_remove_order_customer_remove_order_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_spam',
            field=models.BooleanField(default=False),
        ),
    ]
