# Generated by Django 5.1.4 on 2025-01-14 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_review_is_spam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score_analysis',
            field=models.DecimalField(decimal_places=5, editable=False, max_digits=6, null=True),
        ),
    ]
