# Generated by Django 5.1.4 on 2025-07-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_product_short_description_productthumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, default='', max_length=10000, null=True),
        ),
    ]
