# Generated by Django 5.1.4 on 2025-07-02 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_product_short_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImageFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector_json', models.TextField()),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image_feature', to='store.product')),
            ],
        ),
    ]
