# Generated by Django 5.2.12 on 2026-06-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_useraddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_tracking_code',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
